name: BakaMC
main: cn.bakamc.folia.BakaMCPlugin
version: 0.1
folia-supported: true
authors:
  - forpleuvoir

commands:
  fly:
    description: 飞行
    usage: /fly
    permission: BakaMC.fly
  specialitem:
    description: 特殊物品
    usage: /specialitem
    permission: BakaMC.fly

permissions:
  BakaMC.fly:
    description: baka-fly
    default: true
  BakaMC.admin:
    description: 管理员
    default: false