name: BakaMC
main: cn.bakamc.folia.BakaMCPlugin
version: 0.1
folia-supported: true
authors:
  - forpleuvoir

commands:
  fly:
    description: 飞行
    usage: /fly
    permission: bakamc.fly
  specialitem:
    description: 特殊物品
    usage: /specialitem
    permission: bakamc.admin

permissions:
  bakamc.admin:
    description: 管理员
    default: op
  bakamc.fly:
    description: 飞行
    default: true