name: ${name}
main: cn.bakamc.folia.BakaMCPlugin
version: ${version}
folia-supported: true
api-version: ${apiVersion}
description: ${description}

authors:
  - forpleuvoir

commands:
  fly:
    description: 飞行
    usage: /fly
    permission: bakamc.fly
  specialitem:
    description: 特殊物品
    usage: /specialitem
    permission: bakamc.admin
  bakamc:
    description: BakaMC插件指令
    usage: /bakamc
    permission: bakamc.admin
  end:
    description: 打开末影箱
    usage: /end
    permission: bakamc.end

permissions:
  bakamc.admin:
    description: 管理员
    default: op
  bakamc.fly:
    description: 飞行
    default: true
  bakamc.end:
    description: 末影箱
    default: op