# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: reobfJar

on:
  schedule:
    - cron: "0 23 ? * 2,4,6"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: c
      run: chmod +x ./testbench
    
    - name: rebofJar
      run: ./gradlew reobfJar

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
          name: Artifacts
          path: build/libs/
      
